In [4]:
# Simulation and Modeling Lab
# Course: CSE 413
# Name: Mehedi Hassan Bhuiyan
# Student ID: 0432320005101080
# Lab 2

In [5]:
import numpy as np

#student id 0432320005101080
d1 = 0
d2 = 8

#create matrix A
A = np.array([
    [d1 + 2, d2 + 1],
    [2 * d1, d2 + 2]
])

print(A)

[[ 2  9]
 [ 0 10]]


In [6]:
#shape
print("Shape:", A.shape)

#determinant
det_A = np.linalg.det(A)
print("Determinant:", det_A)

#rank
print("Rank:", np.linalg.matrix_rank(A))

#eigenvalues
print("Eigenvalues:", np.linalg.eigvals(A))

#inverse
if det_A != 0:
    print("Inverse:")
    print(np.linalg.inv(A))
else:
    print("Inverse does not exist")

Shape: (2, 2)
Determinant: 20.000000000000007
Rank: 2
Eigenvalues: [ 2. 10.]
Inverse:
[[ 0.5  -0.45]
 [ 0.    0.1 ]]


In [7]:
#change one value
B = A.copy()

#add 1 to the first element
B[0,0] = B[0,0] + 1

print("Matrix B:")
print(B)

print("Changed element: A[0,0]")
print("Value changed from 2 to 3")

Matrix B:
[[ 3  9]
 [ 0 10]]
Changed element: A[0,0]
Value changed from 2 to 3


In [8]:
#shape
print("Shape:", B.shape)

#determinant
det_B = np.linalg.det(B)
print("Determinant:", det_B)

#rank
print("Rank:", np.linalg.matrix_rank(B))

#eigenvalues
print("Eigenvalues:", np.linalg.eigvals(B))

#inverse
if det_B != 0:
    print("Inverse:")
    print(np.linalg.inv(B))
else:
    print("Inverse does not exist")

Shape: (2, 2)
Determinant: 30.000000000000014
Rank: 2
Eigenvalues: [ 3. 10.]
Inverse:
[[ 0.33333333 -0.3       ]
 [ 0.          0.1       ]]


In [ ]:
'''Comparison & Explanation

 1. How did the determinant change and why?

The determinant of Matrix A was 20, while the determinant of Matrix B was 30.
The determinant increased by 10 because one element of the matrix was increased by 1, which changed the overall product used in the determinant calculation.

 2. Did the rank change? Explain.

The rank did not change. Both Matrix A and Matrix B have a rank of 2.
Both matrices still have two linearly independent rows, so changing one element did not make the matrix singular.

 3. How did the eigenvalues respond to the value change?

The eigenvalues changed from 2 and 10 in Matrix A to 3 and 10 in Matrix B.
The eigenvalue corresponding to the changed diagonal element increased from 2 to 3, while the other eigenvalue remained 10.

4. Is B easier or harder to invert than A? Why?

Both A and B are invertible because their determinants are non-zero.
Therefore, neither matrix is significantly easier or harder to invert. Both have a simple 2×2 structure and their inverses can be calculated using NumPy.'''